name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    uses: cdqag/workflow-public/.github/workflows/release-action.yaml@v1
    with:
      runs-on: ubuntu-latest
